export interface StateInfo {
  slug: string;
  name: string;
  abbr: string;
  dmvName: string;
  dmvUrl: string;
  manualUrl: string;
  testFee: string;
  waitPeriod: string;
  minAge: string;
  notes: string;
}

export const states: StateInfo[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", dmvName: "Alabama ALEA", dmvUrl: "https://www.alea.gov/dps/driver-license/commercial-driver-license", manualUrl: "https://www.alea.gov/sites/default/files/inline-files/CDL_Manual.pdf", testFee: "$20–$36", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Alabama requires a medical examiner's certificate on file with the CDL. CDL skills tests are conducted at third-party test sites." },
  { slug: "alaska", name: "Alaska", abbr: "AK", dmvName: "Alaska DMV", dmvUrl: "https://doa.alaska.gov/dmv/cdl/index.htm", manualUrl: "https://doa.alaska.gov/dmv/docs/cdlmanual.pdf", testFee: "$15–$50", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Alaska has unique CDL provisions for drivers operating in remote areas. Some waiver programs exist for rural residents." },
  { slug: "arizona", name: "Arizona", abbr: "AZ", dmvName: "Arizona MVD", dmvUrl: "https://azdot.gov/motor-vehicles/driver-services/commercial-driver-license", manualUrl: "https://azdot.gov/sites/default/files/media/publication/2021/arizona-commercial-driver-license-manual.pdf", testFee: "$25–$50", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Arizona uses third-party CDL skills testers. The state has no waiting period beyond the federal 14-day CLP requirement." },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", dmvName: "Arkansas DFA", dmvUrl: "https://www.dfa.arkansas.gov/driver-services/commercial-driver-license/", manualUrl: "https://www.dfa.arkansas.gov/images/uploads/driverServicesOffice/arkansas_cdl_manual.pdf", testFee: "$20–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Arkansas CDL knowledge tests are taken at revenue office locations. Skills tests are conducted by certified third-party testers." },
  { slug: "california", name: "California", abbr: "CA", dmvName: "California DMV", dmvUrl: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/commercial-driver-licenses-cdl/", manualUrl: "https://www.dmv.ca.gov/portal/uploads/2020/06/California-Commercial-Driver-Handbook.pdf", testFee: "$35–$75", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "California CDL applicants should note the state has some of the strictest emissions and weight regulations. Appointments are required at most DMV offices." },
  { slug: "colorado", name: "Colorado", abbr: "CO", dmvName: "Colorado DMV", dmvUrl: "https://dmv.colorado.gov/commercial-drivers-license", manualUrl: "https://dmv.colorado.gov/sites/dmv/files/documents/DR2501.pdf", testFee: "$20–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Colorado offers CDL knowledge tests at select driver license offices. Third-party skills testers are used throughout the state." },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", dmvName: "Connecticut DMV", dmvUrl: "https://portal.ct.gov/DMV/License/CDL/Commercial-Driver-s-License", manualUrl: "https://portal.ct.gov/-/media/DMV/Commercial/CDL_Manual_English.pdf", testFee: "$40–$80", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Connecticut requires CDL applicants to pass both the knowledge and skills tests through DMV-approved facilities." },
  { slug: "delaware", name: "Delaware", abbr: "DE", dmvName: "Delaware DMV", dmvUrl: "https://www.dmv.de.gov/VehicleServices/CDL/", manualUrl: "https://www.dmv.de.gov/VehicleServices/CDL/documents/CDL_Manual.pdf", testFee: "$25–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Delaware CDL tests are administered at the Dover and Wilmington DMV offices." },
  { slug: "florida", name: "Florida", abbr: "FL", dmvName: "Florida HSMV", dmvUrl: "https://www.flhsmv.gov/driver-licenses-id-cards/commercial-driver-license/", manualUrl: "https://www.flhsmv.gov/pdf/handbooks/cdlhb.pdf", testFee: "$25–$75", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Florida has one of the largest CDL workforces in the country. Third-party CDL skills testing is widely available throughout the state." },
  { slug: "georgia", name: "Georgia", abbr: "GA", dmvName: "Georgia DDS", dmvUrl: "https://dds.georgia.gov/commercial-drivers-license", manualUrl: "https://dds.georgia.gov/sites/dds.georgia.gov/files/related_files/site_page/CDLManual.pdf", testFee: "$32–$70", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Georgia requires CDL applicants to schedule skills tests through approved third-party testing companies." },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", dmvName: "Hawaii DMV", dmvUrl: "https://www.hawaii.gov/dot/highways/hwy-div/cdl/", manualUrl: "https://hidot.hawaii.gov/highways/files/2015/09/CDL-Manual.pdf", testFee: "$25–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Hawaii CDL regulations apply primarily to inter-island commercial operations. Contact the county licensing office on your island for specific requirements." },
  { slug: "idaho", name: "Idaho", abbr: "ID", dmvName: "Idaho DMV", dmvUrl: "https://itd.idaho.gov/dmv/cdl/", manualUrl: "https://itd.idaho.gov/dmv/cdl/docs/CDLManual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Idaho allows third-party CDL skills testers. The state has specific provisions for agricultural CDL waivers for farm operations." },
  { slug: "illinois", name: "Illinois", abbr: "IL", dmvName: "Illinois SOS", dmvUrl: "https://www.ilsos.gov/departments/drivers/cdl/", manualUrl: "https://www.ilsos.gov/publications/pdf_publications/dsd_a132.pdf", testFee: "$30–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Illinois uses a combination of state and third-party CDL skills testing sites. Chicago metro applicants should expect longer appointment wait times." },
  { slug: "indiana", name: "Indiana", abbr: "IN", dmvName: "Indiana BMV", dmvUrl: "https://www.in.gov/bmv/driver-requirements-and-safety/commercial-driver-license/", manualUrl: "https://www.in.gov/bmv/files/CDL_Manual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Indiana BMV offers CDL testing at all full-service license branches. Third-party skills testing is also available." },
  { slug: "iowa", name: "Iowa", abbr: "IA", dmvName: "Iowa DOT", dmvUrl: "https://iowadot.gov/mvd/driverslicense/CDL", manualUrl: "https://iowadot.gov/mvd/files/cdlmanual.pdf", testFee: "$20–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Iowa has a strong agricultural trucking industry. Farm waiver CDL options exist for certain intrastate agricultural operations." },
  { slug: "kansas", name: "Kansas", abbr: "KS", dmvName: "Kansas DMV", dmvUrl: "https://www.ksrevenue.gov/dovcdl.html", manualUrl: "https://www.ksrevenue.gov/pdf/cdlmanual.pdf", testFee: "$20–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Kansas offers CDL testing at county treasurer offices statewide. Third-party skills testing is widely available." },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", dmvName: "Kentucky KYTC", dmvUrl: "https://transportation.ky.gov/Drivers-License/Pages/Commercial-Driver-License.aspx", manualUrl: "https://transportation.ky.gov/Drivers-License/Documents/Kentucky%20CDL%20Manual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Kentucky uses third-party CDL skills testers throughout the state. The state has a strong coal and manufacturing trucking sector." },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", dmvName: "Louisiana OMV", dmvUrl: "https://www.expresslane.org/Pages/cdl.aspx", manualUrl: "https://www.expresslane.org/cdl/documents/cdlmanual.pdf", testFee: "$18–$50", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Louisiana CDL applicants can visit any Office of Motor Vehicles location for knowledge tests. Petrochemical and port trucking jobs are plentiful." },
  { slug: "maine", name: "Maine", abbr: "ME", dmvName: "Maine BMV", dmvUrl: "https://www.maine.gov/sos/bmv/licenses/cdl.html", manualUrl: "https://www.maine.gov/sos/bmv/licenses/documents/CDLManual.pdf", testFee: "$30–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Maine uses third-party CDL testers. The state has forest products and agricultural trucking exemptions." },
  { slug: "maryland", name: "Maryland", abbr: "MD", dmvName: "Maryland MVA", dmvUrl: "https://mva.maryland.gov/drivers/Pages/cdl-info.aspx", manualUrl: "https://mva.maryland.gov/drivers/Documents/cdlmanual.pdf", testFee: "$30–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Maryland MVA requires CDL knowledge tests at MVA branch offices. The state is a major trucking hub due to its Mid-Atlantic ports." },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", dmvName: "Massachusetts RMV", dmvUrl: "https://www.mass.gov/cdl-commercial-driver-license", manualUrl: "https://www.mass.gov/doc/2022-commercial-driver-license-manual/download", testFee: "$30–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Massachusetts RMV requires CDL applicants to book appointments online. The state has strict diesel emission regulations affecting older trucks." },
  { slug: "michigan", name: "Michigan", abbr: "MI", dmvName: "Michigan SOS", dmvUrl: "https://www.michigan.gov/sos/vehicle-registration/driver-license/commercial-driver-license", manualUrl: "https://www.michigan.gov/sos/-/media/Project/Websites/sos/cdl-manual.pdf", testFee: "$25–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Michigan uses the DRIVE system for CDL scheduling. Third-party skills testing is available at approved sites across the state." },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", dmvName: "Minnesota DVS", dmvUrl: "https://dps.mn.gov/divisions/dvs/Pages/cdl.aspx", manualUrl: "https://dps.mn.gov/divisions/dvs/forms-documents/Documents/CDLmanual.pdf", testFee: "$20–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Minnesota offers CDL testing at driver's license exam stations. Agricultural CDL waivers are available for qualified farm operations." },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", dmvName: "Mississippi DPS", dmvUrl: "https://www.dps.state.ms.us/driver-services/commercial-drivers-license/", manualUrl: "https://www.dps.state.ms.us/wp-content/uploads/2021/01/CDL-Manual.pdf", testFee: "$15–$35", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Mississippi uses third-party CDL skills testers. The state has exemptions for agriculture and firefighting vehicles." },
  { slug: "missouri", name: "Missouri", abbr: "MO", dmvName: "Missouri DOR", dmvUrl: "https://dor.mo.gov/driver-license/commercial/", manualUrl: "https://dor.mo.gov/forms/driver-guides/CDLManual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Missouri uses third-party CDL skills testing at approved locations statewide. The state is a major freight corridor with high CDL demand." },
  { slug: "montana", name: "Montana", abbr: "MT", dmvName: "Montana MVD", dmvUrl: "https://doj.mt.gov/driving/cdl/", manualUrl: "https://doj.mt.gov/wp-content/uploads/2021/cdl-manual.pdf", testFee: "$15–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Montana has agricultural and farm vehicle exemptions from full CDL requirements. The state is large geographically with limited DMV locations — plan ahead." },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", dmvName: "Nebraska DMV", dmvUrl: "https://dmv.nebraska.gov/cdl", manualUrl: "https://dmv.nebraska.gov/sites/dmv.nebraska.gov/files/cdl-manual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Nebraska offers CDL knowledge tests at all driver licensing offices. Agricultural CDL exemptions apply to certain farm equipment operations." },
  { slug: "nevada", name: "Nevada", abbr: "NV", dmvName: "Nevada DMV", dmvUrl: "https://dmv.nv.gov/cdl/", manualUrl: "https://dmv.nv.gov/forms/cdlmanual.pdf", testFee: "$25–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Nevada CDL applicants can test at DMV offices in Las Vegas, Reno, and Carson City. The state has high demand for CDL drivers in gaming and construction industries." },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", dmvName: "New Hampshire DMV", dmvUrl: "https://www.nh.gov/safety/divisions/dmv/driver-licensing/commercial/index.htm", manualUrl: "https://www.nh.gov/safety/divisions/dmv/documents/cdl-manual.pdf", testFee: "$30–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "New Hampshire requires CDL applicants to visit DMV offices in Concord or regional offices for testing." },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", dmvName: "New Jersey MVC", dmvUrl: "https://www.nj.gov/mvc/drivertopics/CDL.htm", manualUrl: "https://www.nj.gov/mvc/pdf/vehicles/CDLManual.pdf", testFee: "$30–$85", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "New Jersey MVC is one of the busiest licensing agencies in the US — make appointments early. The state is a major northeast logistics hub." },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", dmvName: "New Mexico MVD", dmvUrl: "https://www.mvd.newmexico.gov/driver-services/commercial-drivers-license/", manualUrl: "https://www.mvd.newmexico.gov/documents/cdlmanual.pdf", testFee: "$18–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "New Mexico uses third-party CDL skills testers. The state has oil and gas industry trucking jobs in high demand." },
  { slug: "new-york", name: "New York", abbr: "NY", dmvName: "New York DMV", dmvUrl: "https://dmv.ny.gov/driver-license/commercial-driver-license-cdl-information", manualUrl: "https://dmv.ny.gov/brochure/commercial-driver-s-license-manual", testFee: "$50–$100", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "New York has some of the highest CDL test fees in the nation. NYC metro applicants should book appointments weeks in advance due to high demand." },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", dmvName: "North Carolina DMV", dmvUrl: "https://www.ncdot.gov/dmv/license-id/driver-licenses/commercial-license/Pages/default.aspx", manualUrl: "https://www.ncdot.gov/dmv/license-id/driver-licenses/commercial-license/Documents/CDL-Manual.pdf", testFee: "$20–$50", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "North Carolina uses third-party CDL skills testers. The state has strong trucking demand from its manufacturing and agriculture sectors." },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", dmvName: "North Dakota DOT", dmvUrl: "https://www.dot.nd.gov/divisions/driverslicense/cdl.htm", manualUrl: "https://www.dot.nd.gov/divisions/driverslicense/docs/CDL-Manual.pdf", testFee: "$15–$35", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "North Dakota has agricultural CDL exemptions for farm vehicles. Oil industry trucking in the Bakken region drives high CDL demand." },
  { slug: "ohio", name: "Ohio", abbr: "OH", dmvName: "Ohio BMV", dmvUrl: "https://www.bmv.ohio.gov/dl-cdl.aspx", manualUrl: "https://www.bmv.ohio.gov/downloads/bmv5505.pdf", testFee: "$20–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Ohio uses third-party CDL skills testers. The state is a major freight corridor at the intersection of I-70 and I-75." },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", dmvName: "Oklahoma DPS", dmvUrl: "https://www.ok.gov/dps/Driver_Licensing_Division/Commercial_Driver_License_(CDL)/", manualUrl: "https://www.ok.gov/dps/documents/CDL_Manual.pdf", testFee: "$20–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Oklahoma uses third-party CDL skills testers. The energy sector (oil, gas) creates strong CDL demand across the state." },
  { slug: "oregon", name: "Oregon", abbr: "OR", dmvName: "Oregon DMV", dmvUrl: "https://www.oregon.gov/odot/dmv/pages/driverid/cdl.aspx", manualUrl: "https://www.oregon.gov/odot/dmv/docs/cdlmanual.pdf", testFee: "$25–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Oregon uses third-party CDL skills testers. The state has strict size and weight restrictions especially on state highways." },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", dmvName: "Pennsylvania PennDOT", dmvUrl: "https://www.penndot.pa.gov/TravelInPA/Pages/Commercial-Driver-s-License.aspx", manualUrl: "https://www.penndot.pa.gov/TravelInPA/cdl-manual/CDLManual.pdf", testFee: "$35–$70", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Pennsylvania is a top-5 CDL state by workforce. PennDOT uses driver license centers statewide for knowledge tests and approved third parties for skills tests." },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", dmvName: "Rhode Island DMV", dmvUrl: "https://dmv.ri.gov/licenses-permits-ids/driver-licenses/commercial-drivers-license-cdl", manualUrl: "https://dmv.ri.gov/sites/g/files/xkgbur1011/files/documents/CDLManual.pdf", testFee: "$30–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Rhode Island is the smallest state but has significant CDL demand due to its port and logistics industries." },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", dmvName: "South Carolina DMV", dmvUrl: "https://www.scdmvonline.com/Driver-Services/CDL", manualUrl: "https://www.scdmvonline.com/documents/CDL-Manual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "South Carolina uses third-party CDL skills testers. Port of Charleston activity drives significant CDL employment in the state." },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", dmvName: "South Dakota DPS", dmvUrl: "https://dps.sd.gov/driver-licensing/cdl/", manualUrl: "https://dps.sd.gov/Driver-Licensing/CDL/CDL-Manual.pdf", testFee: "$15–$35", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "South Dakota has agricultural CDL exemptions for farm vehicle operators. CDL tests are available at driver exam stations statewide." },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", dmvName: "Tennessee DOS", dmvUrl: "https://www.tn.gov/safety/driver-services/cdl.html", manualUrl: "https://www.tn.gov/content/dam/tn/safety/documents/CDL-Manual.pdf", testFee: "$20–$45", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Tennessee uses third-party CDL skills testers. Nashville and Memphis are major logistics hubs with strong CDL job markets." },
  { slug: "texas", name: "Texas", abbr: "TX", dmvName: "Texas DPS", dmvUrl: "https://www.dps.texas.gov/section/driver-license/commercial-driver-license", manualUrl: "https://www.dps.texas.gov/sites/default/files/documents/drivers-license/CDLManual.pdf", testFee: "$25–$61", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Texas is the largest CDL state by workforce. DPS offices can have long wait times — book appointments early. The oil and gas industry drives strong CDL demand." },
  { slug: "utah", name: "Utah", abbr: "UT", dmvName: "Utah DVS", dmvUrl: "https://dld.utah.gov/cdl/", manualUrl: "https://dld.utah.gov/wp-content/uploads/sites/16/2020/08/CDL-Manual.pdf", testFee: "$25–$50", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Utah uses third-party CDL skills testers. The state's growing logistics sector around Salt Lake City creates strong CDL demand." },
  { slug: "vermont", name: "Vermont", abbr: "VT", dmvName: "Vermont DMV", dmvUrl: "https://dmv.vermont.gov/licenses/cdl", manualUrl: "https://dmv.vermont.gov/sites/dmv/files/documents/DMV-CDL-Manual.pdf", testFee: "$30–$60", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Vermont CDL applicants test at DMV offices in Montpelier and other regional locations. The state has agricultural CDL exemptions." },
  { slug: "virginia", name: "Virginia", abbr: "VA", dmvName: "Virginia DMV", dmvUrl: "https://www.dmv.virginia.gov/drivers/cdl/", manualUrl: "https://www.dmv.virginia.gov/webdoc/pdf/cdl_manual.pdf", testFee: "$20–$50", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Virginia uses third-party CDL skills testers. Northern Virginia and Hampton Roads are major CDL employment markets." },
  { slug: "washington", name: "Washington", abbr: "WA", dmvName: "Washington DOL", dmvUrl: "https://www.dol.wa.gov/driverslicense/cdl.html", manualUrl: "https://www.dol.wa.gov/sites/default/files/2022-04/cdlmanual.pdf", testFee: "$30–$75", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Washington uses third-party CDL skills testers. The state has strict commercial vehicle regulations and Seattle-area logistics is a major employer." },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", dmvName: "West Virginia DMV", dmvUrl: "https://transportation.wv.gov/DMV/drivers/Pages/Commercial-Driver-License.aspx", manualUrl: "https://transportation.wv.gov/DMV/drivers/Documents/CDL-Manual.pdf", testFee: "$20–$40", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "West Virginia uses third-party CDL skills testers. The state's mining and energy industries drive strong CDL demand." },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", dmvName: "Wisconsin DMV", dmvUrl: "https://www.dot.state.wi.us/drivers/cdl/", manualUrl: "https://www.dot.state.wi.us/drivers/cdl/docs/cdl-manual.pdf", testFee: "$20–$55", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Wisconsin uses third-party CDL skills testers. Agricultural CDL exemptions exist for certain farm vehicle operators." },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", dmvName: "Wyoming DOT", dmvUrl: "https://www.dot.state.wy.us/home/driver_license_records/commercial_driver_license.html", manualUrl: "https://www.dot.state.wy.us/files/live/sites/wydot/files/shared/Driver_Services/CDL/cdl-manual.pdf", testFee: "$15–$35", waitPeriod: "14 days (federal minimum)", minAge: "18 (intrastate), 21 (interstate)", notes: "Wyoming CDL applicants test at driver license offices statewide. The energy and ranching industries drive significant CDL demand." },
];

export const statesBySlug: Record<string, StateInfo> = Object.fromEntries(
  states.map((s) => [s.slug, s])
);

export function getState(slug: string): StateInfo | undefined {
  return statesBySlug[slug];
}

export function getAllStateSlugs(): string[] {
  return states.map((s) => s.slug);
}
